name: Lighthouse Performance Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Wait for deployment
      uses: lewagon/wait-on-check-action@v1.3.1
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.ref }}
        check-name: 'Deploy to Vercel'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v11
      with:
        urls: |
          ${{ secrets.SITE_URL }}
          ${{ secrets.SITE_URL }}/about
          ${{ secrets.SITE_URL }}/books
          ${{ secrets.SITE_URL }}/lists
          ${{ secrets.SITE_URL }}/lists/new
          ${{ secrets.SITE_URL }}/contact
          ${{ secrets.SITE_URL }}/sign-in
        configPath: './.lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-results-${{ github.run_id }}
        path: |
          .lighthouseci/
          lhci_reports/
        retention-days: 30
      